### ISSUE TITLE
Can not build project at Windows !!

### ISSUE THREAD

**Issue by CMingTseng** [softartdev/NoteDelight#413]
Dear Sir  very thx your project 

let me know how use SQLDelight & sqlite 

i can build this projetc  at  mac & linux 

but i get error at  Windows !!

 Could not create task ':shared:compileDebugJavaWithJavac !!
 
 Caused by: org.gradle.jvm.toolchain.internal.NoToolchainAvailableException: No matching toolchains found for requested specification: {languageVersion=11, vendor=any, implementation=vendor-specific} for WINDOWS on x86_64.
	at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.downloadToolchain(JavaToolchainQueryService.java:180)
	at org.gradle.jvm.toolchain.internal.JavaToolchainQueryService.lambda$query$2(JavaToolchainQueryService.java:146)
	
	Failed building KotlinMPPGradleModel  jvmToolchain(11)  

Caused by: org.gradle.api.internal.provider.AbstractProperty$PropertyQueryException: Failed to calculate the value of task ':shared:compileDebugJavaWithJavac' property 'javaCompiler'.

	Execution failed for task ':shared-jvm-util:compileKotlin'.
> 'compileJava' task (current target is 11) and 'compileKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain
	
	
	i try to modify 
	
	 jvmToolchain(11)  -->  jvmToolchain(17)  at build.gradle.kts at  "shared" & "shared-compose-ui"
	 
	  toolchain { languageVersion.set(JavaLanguageVersion.of(11) --> toolchain { languageVersion.set(JavaLanguageVersion.of(17)  at build.gradle.kts at  "shared-jvm-util" 
	  
	  &
	  
	 mainClass = "MainKt" -->    mainClass = "com.softartdev.notedelight.MainKt"  at build.gradle.kts at  "desktop-compose-app"
	(at  mac/linux   here also must change !!  ) 
	 
	 the JVM version is work !! 
	 
	 but   Android version still not build  
	 
	 i still get JavaWithJavac task error
	 
	 
	 my os is  WIndows 10 pro x64 + AS (Flamingo + Giraffe )
	
Android Studio Flamingo | 2022.2.1 Patch 2
Build #AI-222.4459.24.2221.10121639, built on May 12, 2023
Runtime version: 17.0.6+0-b2043.56-9586694 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    gradle.version.catalogs.dynamic.support=true
    
    Android Studio Giraffe | 2022.3.1
Build #AI-223.8836.35.2231.10406996, built on June 29, 2023
Runtime version: 17.0.6+0-b2043.56-10027231 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    
    THX

**Comment by softartdev** [comment]
Dear CMingTseng,

Thank you for showing interest in our project!

I regret to inform you that I don't currently have access to a Windows machine to directly investigate the issue you mentioned.

However, if you find a solution to the problem, we encourage you to submit a pull request and become a contributor to the project..

Best regards!

**Comment by softartdev** [comment]
Sorry if it's too late, we fixed the Windows build by [adding toolchain resolver plugin](https://github.com/softartdev/NoteDelight/commit/456ce1dcd7ef6098325298eeafc34c8cd003a779#diff-5625e3601fa0ad3a6a2824239e5a2fde71c149597d31394f9224a08c24be7b9dR20), check this [out](https://github.com/softartdev/NoteDelight/actions/runs/7091844050/job/19301873544#step:7:16).
