### ISSUE TITLE
desktop-compose-app JVM Crash  at Windows & Mac 

### ISSUE THREAD

**Issue by CMingTseng** [softartdev/NoteDelight#416]
Dear Sir

if run "desktop-compose-app" at Windows ( must do some modify gradle) & Mac 

add a new Note  

and then Click "T"

will crash !!

java.lang.NullPointerException: ResultSet returned null for Note.sq:getById
	at app.cash.sqldelight.ExecutableQuery.executeAsOne(Query.kt:189)
	at com.softartdev.notedelight.shared.data.NoteUseCase.loadNote(NoteUseCase.kt:77)
	
![image](https://github.com/softartdev/NoteDelight/assets/7948140/47540a72-f0f3-4a35-bb9d-5c30dcac8eea)

![image](https://github.com/softartdev/NoteDelight/assets/7948140/ac1a8b3d-8104-412c-a84a-058625dc8b1e)

 ![unnamed](https://github.com/softartdev/NoteDelight/assets/7948140/21883739-e7a7-42dc-b495-d1db21041148)
THX

**Comment by softartdev** [comment]
Thanks for noticing this issue! For this case, I [added special UI-test](https://github.com/softartdev/NoteDelight/commit/1a59a1aafe5bd9ecc2dc3ce517696a1707b02fbe). There were merge conflicts in your changes, so we [added your solution separately](https://github.com/softartdev/NoteDelight/commit/81be21eda04ce4086a48a9c01f32e6129ac306df).

**Comment by CMingTseng** [comment]
> 感謝您注意到這個問題！對於這種情況，我[添加了特殊的 UI-test](https://github.com/softartdev/NoteDelight/commit/1a59a1aafe5bd9ecc2dc3ce517696a1707b02fbe)。您的更改中存在合併衝突，因此我們[單獨添加了您的解決方案](https://github.com/softartdev/NoteDelight/commit/81be21eda04ce4086a48a9c01f32e6129ac306df)。

__________________________
Dear Sir

Thanks for using my PR

Although there are some conflicts
But please refer to other branches as well.
Because I have three environments: Android/Windows/mac

In the desktop-compose-app section

I found that the toolchain of the Windows JVM has a big problem

Need to upgrade to 17
Otherwise when compiling
will not be able to handle in the javadoc section

"Caused by: org.gradle.api.internal.provider.AbstractProperty$PropertyQueryException: Failed to calculate the value of task ':shared:compileDebugJavaWithJavac' property 'javaCompiler'."



The relevant ISSUE I have provided is here https://github.com/softartdev/NoteDelight/issues/413
Then this is the part I corrected after fork

https://github.com/softartdev/NoteDelight/commit/ed5c7388b94d6259aec82f8d844420dccae7d3d2

Currently, there is an occasional problem when init/compiling on Windows.

It’s just that Windows doesn’t have xcode

"libs.plugins.kotlin.cocoapods/ kotlin("native.cocoapods")" This part requires the use of cocoapods

Occasionally cause Windows to stop during the init project!!

I would have liked to use

" Detect HOST OS -- org.gradle.internal.os.OperatingSystem.current().isMacOsX)"

 To enable or disable loading this plugin --kotlin("native.cocoapods")
 
 but!!!  when closing kotlin("native.cocoapods")  the  cocoapods {} will still be tried to load

Cause cocoapods cannot be parsed

Can try fix it ?

https://github.com/softartdev/NoteDelight/commit/870f91ed5f5964244c9986f5be47a2af15e6e907

____________________
another question

Because I want to learn/practice using sqlite as DB (a money-saving DB micro system that does not require mongodb/postgresql)

Then see the pictures in ReadME
https://github.com/softartdev/NoteDelight/blob/master/screenshoots/android/dark/1.png

So after trying to join the User table
It can be used by multiple people or WebUI+backend (by API) or WebUI+Web_Admin_UI( for add new user ,del user) +backend (by API)

But currently there is no way to have asynchronous operations in the sqlite part (CRUD) of the backend (using ktor server)

The API Call cannot respond

I wonder if I can give a demonstration here?

**Comment by softartdev** [comment]
I have seen all your issues and pull requests and will try to find time to review them, so thanks for your great interest in my project.

I'll set up a Windows VM to debug build on that OS shortly and check your issues and pull requests. I already knew about problems with Windows [from CI](https://github.com/softartdev/NoteDelight/actions/runs/6067031650/job/16458254785#step:6:52), which helps to find many problems automatically.

Regarding your other question about web platform support. I didn't understand your suggestion enough.
In general, I planned to support the web platform as a single user application, as well as for other platforms.
Also, I've been planning for a long time to support syncing database backups to the cloud (probably Google Drive and maybe some others). This feature will allow the user to share their database between devices.
And another long-standing plan is support for sign-in into the application with a fingerprint.
But first, I want to [support encryption in the desktop version of the application](https://github.com/softartdev/NoteDelight#work-in-progress-).

I don't really imagine the use of such an application by multiple people, so of course show your idea here.

**Comment by CMingTseng** [comment]
> I have seen all your issues and pull requests and will try to find time to review them, so thanks for your great interest in my project.
> 
> I'll set up a Windows VM to debug build on that OS shortly and check your issues and pull requests. I already knew about problems with Windows [from CI](https://github.com/softartdev/NoteDelight/actions/runs/6067031650/job/16458254785#step:6:52), which helps to find many problems automatically.
> 
> Regarding your other question about web platform support. I didn't understand your suggestion enough. In general, I planned to support the web platform as a single user application, as well as for other platforms. Also, I've been planning for a long time to support syncing database backups to the cloud (probably Google Drive and maybe some others). This feature will allow the user to share their database between devices. And another long-standing plan is support for sign-in into the application with a fingerprint. But first, I want to [support encryption in the desktop version of the application](https://github.com/softartdev/NoteDelight#work-in-progress-).
> 
> I don't really imagine the use of such an application by multiple people, so of course show your idea here.

@softartdev 


I apologize for any confusion in my description. The reason I am currently referencing this project is for working with SQLite using SQLDelight.

As an Android engineer looking to transition to backend development, I've noticed that backend databases typically involve larger systems such as MySQL, MongoDB, or PostgreSQL. However, for practice purposes and due to my familiarity with Kotlin through Android development, I have chosen to use Kotlin (ktor) and SQLite as the entry point for practicing CRUD operations on a backend API server.

I have already been able to use SQLite to a basic extent through your project. However, I am facing some challenges with CRUD operations and Kotlin coroutines. In this project, Notes are queried based on their ID (AUTOINCREMENT), so there are situations where it does not return a Note (i.e., Note=null).

kotlin
Copy code
@Throws(Exception::class)
suspend fun loadNote(noteId: Long): Note = dbRepo.noteQueries.getById(noteId).executeAsOne()
But in other scenarios, such as getByTitle or getByName, there might be a return null ( Note=null /Note? ). 

How should I handle this?

Additionally, as a backend API server, when I receive a request from the client through Ktor's Route and perform a database query, I use Kotlin coroutines. However, I am unsure about how to handle the call.respond part. Can you provide an example?

I have forked your project to create a separate practice project. In this project, I plan to add multiple users (practicing CRUD operations on the User table) and then connect them with Notes (practicing operations like JOIN between two tables).

https://github.com/cybernhl/Ktor_JWT

Regarding the UI for the client-side, apart from the original Android, desktop, and iOS components, I plan to add a web component (currently using Kotlin-JS, potentially Kotlin Compose in the future).

For the backend API server part, I also intend to practice designing OpenAPI and an Admin GUI. Most backends have an Admin page for user management tasks like enabling/disabling accounts and password changes, so that's on my roadmap as well.

THX

This outlines my general plan, and I appreciate your understanding as I use your project as a learning and practice resource.

**Comment by softartdev** [comment]
I am very glad that my project inspired you to fork it and implement the server part and other features.

If you need to understand nullability in Kotlin, I advise you to read the [documentation](https://kotlinlang.org/docs/java-to-kotlin-nullability-guide.html), or even better, a [book](https://www.manning.com/books/kotlin-in-action) from the creators of the language, where this topic is fully covered.

P.S. It would be better if your fork pointed to a repository (as is [common practice on GitHub](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/about-forks#about-forks)), but this is not required.
